# Generated by Django 5.0.1 on 2025-10-20 23:22

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('geoserver', 'Geoserver'), ('umap', 'uMap'), ('traccar', 'Traccar'), ('keycloak', 'KeyCloak')], max_length=50, unique=True)),
                ('website_url', models.URLField()),
                ('db_host', models.CharField(blank=True, max_length=100, null=True)),
                ('db_port', models.IntegerField(blank=True, default=5432, null=True)),
                ('db_name', models.CharField(blank=True, max_length=100, null=True)),
                ('db_user', models.CharField(blank=True, max_length=100, null=True)),
                ('db_password', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('service_user', models.CharField(blank=True, max_length=100, null=True)),
                ('service_password', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('keycloak_realm', models.CharField(blank=True, max_length=100, null=True)),
                ('keycloak_client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('keycloak_client_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Einstellung',
                'verbose_name_plural': 'Einstellungen',
                'db_table': 'settings',
            },
        ),
    ]
