# Generated by Django 5.0.1 on 2025-10-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='geoserver_workspace',
            field=models.CharField(blank=True, help_text="Schema-Name in der Geoserver PostGIS-Datenbank (z.B. 'public' oder 'cite')", max_length=100, null=True, verbose_name='Geoserver Arbeitsbereich'),
        ),
    ]
