# Generated by Django 5.0.1 on 2025-10-22 21:34

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_settings_geoserver_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='traccar_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='API-Token für die Authentifizierung bei Traccar (ersetzt User/Password)', null=True, verbose_name='Traccar API Token'),
        ),
    ]
